-- ==========================================================
-- Sistema de Controle de Estoque
-- Banco de Dados: Firebird 5.0
-- Execute os scripts na ordem apresentada.
-- ==========================================================

-- ==========================================================
-- 1. CRIAR TABELA GRUPO
-- ==========================================================

CREATE TABLE GRUPO (
    CODIGO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_GRUPO PRIMARY KEY (CODIGO)
);

-- ==========================================================
-- 2. CRIAR TABELA PRODUTO
-- ==========================================================

CREATE TABLE PRODUTO (
    CODIGO INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    CODIGO_GRUPO INTEGER NOT NULL,
    DATA_CADASTRO DATE,
    VALOR NUMERIC(18,2),
    CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PRODUTO_GRUPO
        FOREIGN KEY (CODIGO_GRUPO)
        REFERENCES GRUPO(CODIGO)
);

-- ==========================================================
-- 3. DEFINIR DATA PADRÃO PARA NOVOS PRODUTOS
-- ==========================================================

ALTER TABLE PRODUTO
ALTER DATA_CADASTRO SET DEFAULT CURRENT_DATE;

-- ==========================================================
-- Fim do script.
-- Após executar este arquivo, o banco estará pronto
-- para utilização pela aplicação.
-- ==========================================================